---

- name : modify dest database user password
  rds :
    command: modify
    instance_name: "{{ aws_db_instance_name }}"
    region: "{{ aws_db_region }}"
    postgresql_user: 
      user: "{{ item.USER }}"  
      password: "{{ item.PASSWORD }}"
      expire: infinity
    with_items: "{{ aws_db_user }}"
    wait: yes
    wait_timeout: 600
