---

- name : modify database security groups
  rds :
    command: modify
    instance_name: "{{ aws_db_instance_name }}"
    region: "{{ aws_db_region }}"
    vpc_security_groups: "{{ item }}"
    with_items:
   "{{ aws_db_vpc_security_groups }}"
    wait: yes
    wait_timeout: 600

#這邊不確定vpc_security_groups多組時，是否可以一次給，還是要分次給定...